name: flutter_bloc_action
description: A simple util that mix in "action" behavior to popular BLoC package.
version: 0.0.1
author: Mark Abramenko
homepage: https://github.com/mpkander/flutter_bloc_action

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  pedantic: ^1.10.0

flutter:
